### ISSUE TITLE
Unable to Resolve "..child processes... that may need killed manually"

### ISSUE THREAD

**Issue by ghost** [kouphax/lein-cooper#10]
source: https://github.com/kouphax/lein-cooper/blob/master/src/leiningen/cooper.clj#L92-L97

```
❯ lein cooper
07:55:01 electron | Exception in thread "main" java.io.FileNotFoundException: /private/var/folders/hn/glck51w933df7r5jyyh0lnc80000gn/T/form-init606791011975121696.clj (No such file or directory)
07:55:01 electron | 	at java.io.FileInputStream.open0(Native Method)
07:55:01 electron | 	at java.io.FileInputStream.open(FileInputStream.java:195)
07:55:01 electron | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
07:55:01 electron | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
07:55:01 electron | 	at clojure.lang.Compiler.loadFile(Compiler.java:7314)
07:55:01 electron | 	at clojure.main$load_script.invokeStatic(main.clj:275)
07:55:01 electron | 	at clojure.main$init_opt.invokeStatic(main.clj:277)
07:55:01 electron | 	at clojure.main$init_opt.invoke(main.clj:277)
07:55:01 electron | 	at clojure.main$initialize.invokeStatic(main.clj:308)
07:55:01 electron | 	at clojure.main$null_opt.invokeStatic(main.clj:342)
07:55:01 electron | 	at clojure.main$null_opt.invoke(main.clj:339)
07:55:01 electron | 	at clojure.main$main.invokeStatic(main.clj:421)
07:55:01 electron | 	at clojure.main$main.doInvoke(main.clj:384)
07:55:01 electron | 	at clojure.lang.RestFn.invoke(RestFn.java:421)
07:55:01 electron | 	at clojure.lang.Var.invoke(Var.java:383)
07:55:01 electron | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
07:55:01 electron | 	at clojure.lang.Var.applyTo(Var.java:700)
07:55:01 electron | 	at clojure.main.main(main.java:37)
07:55:01 ui       | Exception in thread "main" java.io.FileNotFoundException: /private/var/folders/hn/glck51w933df7r5jyyh0lnc80000gn/T/form-init7457030026975141273.clj (No such file or directory)
07:55:01 ui       | 	at java.io.FileInputStream.open0(Native Method)
07:55:01 ui       | 	at java.io.FileInputStream.open(FileInputStream.java:195)
07:55:01 ui       | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
07:55:01 ui       | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
07:55:01 ui       | 	at clojure.lang.Compiler.loadFile(Compiler.java:7314)
07:55:01 ui       | 	at clojure.main$load_script.invokeStatic(main.clj:275)
07:55:01 ui       | 	at clojure.main$init_opt.invokeStatic(main.clj:277)
07:55:01 ui       | 	at clojure.main$init_opt.invoke(main.clj:277)
07:55:01 ui       | 	at clojure.main$initialize.invokeStatic(main.clj:308)
07:55:01 ui       | 	at clojure.main$null_opt.invokeStatic(main.clj:342)
07:55:01 ui       | 	at clojure.main$null_opt.invoke(main.clj:339)
07:55:01 ui       | 	at clojure.main$main.invokeStatic(main.clj:421)
07:55:01 ui       | 	at clojure.main$main.doInvoke(main.clj:384)
07:55:01 ui       | 	at clojure.lang.RestFn.invoke(RestFn.java:421)
07:55:01 ui       | 	at clojure.lang.Var.invoke(Var.java:383)
07:55:01 ui       | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
07:55:01 ui       | 	at clojure.lang.Var.applyTo(Var.java:700)
07:55:01 ui       | 	at clojure.main.main(main.java:37)

One or more processes have stopped running. In the current
version of lein-cooper this could result in child processes
(i.e. ones spawned by a process that lein-cooper manages)
left hanging that may need killed manually

Sorry about the inconvenience.
```

Unable to kill the processes and actually, I'm not sure what I'm looking for to kill. I've restarted my Laptop to no avail. 🤔

**Comment by ghost** [comment]
I just resolved this by changing the PORT (to: `3448`) on the figwheel server in my `project.clj` file. And when I changed it back to the offending PORT `3449` the error I experienced earlier came back.

Fig-wheel issue then? (I'm just glad I'm unblocked so I can work on my side-project, lol)

**Comment by ghost** [comment]
Unfortunately, I am getting the same error and changing the PORT number isn't helping.

This means I am unable to continue development on my project. Help?

**Comment by ghost** [comment]
Fixed it just now with a simple, `lein repl` and exiting that session :wtf_shrug:

reference: https://github.com/cursive-ide/cursive/issues/369

**Comment by ghost** [comment]
this issue is still occurring

I have to change the port number to something I haven't used in the past to get around this error. quite annoying as I have to do it almost every other session I have time to spend on my project.

Any insights from anyone?

**Comment by darwin** [comment]
https://github.com/kouphax/lein-cooper/pull/8
